version: "3.9"
services:
  handyman:
    container_name: handyman
    image: handyman:latest
    build:
      context: ../handyman
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: "1"
    ports:
      - "8080:8080"
    environment:
      - grpc.server.address=0.0.0.0
  rancher:
    container_name: rancher
    image: rancher:latest
    build:
      context: ../rancher
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: "1"
    ports:
      - "8090:8090"
    environment:
      - grpc.server.address=0.0.0.0
  landscape:
    container_name: landscape
    image: landscape:latest
    build:
      context: ../landscape
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: "1"
    ports:
      - "8085:8085"
    depends_on:
      - handyman
      - rancher
      - postgres
    environment:
      - grpc.client.HandymanService.address=static://handyman:9080
      - grpc.client.RancherService.address=static://rancher:9090
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus:latest
  grafana:
    image: grafana/grafana:latest
