version: "3.9"
services:
  handyman:
    container_name: handyman
    image: handyman:latest
    build: ../handyman
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - grpc.server.address=0.0.0.0
      - spring.data.mongodb.uri=mongodb://mongodb:27017/handyman
      - landscapeAPI.address=http://landscape:8085
  rancher:
    container_name: rancher
    image: rancher:latest
    build: ../rancher
    depends_on:
      - mongodb 
    ports:
      - "8090:8090"
    environment:
      - grpc.server.address=0.0.0.0
      - spring.data.mongodb.uri=mongodb://mongodb:27017/rancher
      - landscapeAPI.address=http://landscape:8085
  landscape:
    container_name: landscape
    image: landscape:latest
    build: ../landscape
    ports:
      - "8085:8085"
    depends_on:
      - handyman
      - rancher
      - postgres
    environment:
      - grpc.client.HandymanService.address=static://handyman:9080
      - grpc.client.RancherService.address=static://rancher:9090
      - spring.datasource.url=jdbc:postgresql://postgres:5432/db
      - spring.datasource.username=user
      - spring.datasource.password=user
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:9091'
    expose:
      - 9091
    ports:
      - "9091:9091"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  db_data:
  prometheus_data: {}
  grafana_data: {}