{
 "title": "Services REST endpoints evaluation time",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Handyman get all users time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(handymanGetAllUsers_seconds_sum[1m]) / increase(handymanGetAllUsers_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handyman update user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(handymanUpdateUser_seconds_sum[1m]) / increase(handymanUpdateUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handyman delete user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(handymanDeleteUser_seconds_sum[1m]) / increase(handymanDeleteUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handyman get user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(handymanGetUser_seconds_sum[1m]) / increase(handymanGetUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handyman create user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(handymanCreateUser_seconds_sum[1m]) / increase(handymanCreateUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Landscape get user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(landscapeGetUser_seconds_sum[1m]) / increase(landscapeGetUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Landscape update user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(landscapeUpdateUser_seconds_sum[1m]) / increase(lanscapeUpdateUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Landscape delete user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(landscapeDeleteUser_seconds_sum[1m]) / increase(landscapeDeleteUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Landscape get all users time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(landscapeGetAllUsers_seconds_sum[1m]) / increase(landscapeGetAllUsers_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Landscape create user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(landscapeCreateUser_seconds_sum[1m]) / increase(landscapeCreateUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rancher delete user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(rancherDeleteUser_seconds_sum[1m]) / increase(rancherDeleteUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rancher update user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(rancherUpdateUser_seconds_sum[1m]) / increase(rancherUpdateUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rancher create user time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(rancherCreateUser_seconds_sum[1m]) / increase(rancherCreateUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rancher get user time",
   "type": "timeseries",
   "description": "Rancher get user time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "increase(rancherGetUser_seconds_sum[1m]) / increase(rancherGetUser_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rancher get all users time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "increase(rancherGetAllUsers_seconds_sum[1m]) / increase(rancherGetAllUsers_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}