server:
  port: 8085
management:
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
grpc:
  client:
    HandymanService:
      address: "localhost:9080"
      negotiation-type: plaintext
    RancherService:
      address: "localhost:9090"
      negotiation-type: plaintext
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: user
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      javax:
        persistence:
          schema-generation:
            database:
              action: update
    show-sql: true