server:
  port: 8080
management:
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,prometheus
      base-path: /
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
grpc:
  server:
    address: 127.0.0.1
    port: 9080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: handyman
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: user
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      javax:
        persistence:
          schema-generation:
            database:
              action: update
    show-sql: true
landscapeAPI:
  address: "http://localhost:8085"