apiVersion: apps/v1
kind: Deployment
metadata:
  name: landscape
spec:
  selector:
    matchLabels:
      app: landscape
  replicas: 1
  template:
    metadata:
      labels:
        app: landscape
    spec:
      containers:
        - name: landscape
          image: landscape:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: grpc.client.HandymanService.address
              value: static://handyman:9080
            - name: grpc.client.RancherService.address
              value: static://rancher:9090
---
apiVersion: v1
kind: Service
metadata:
  name: landscape
spec:
  selector:
    app: landscape
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  type: NodePort
